CC = gcc
all:
	$(CC) pipe-base.c -o pipe-base
	$(CC) pipe-base3.c -o pipe-base3
	$(CC) pipe-pthread2.c -o pipe-pthread2
	$(CC) pipe-advense.c -o pipe-advense
	$(CC) pipe-base2.c -o pipe-base2
	$(CC) pipe-pthread.c -o pipe-pthread

clean:
	rm -rf *.exe
